idf_component_register(
    SRCS
        "main.cpp"
        "classifier.cpp"
        "led_indicator.cpp"
        "sensor.cpp"
        "storage.cpp"
        "test_storage.cpp"
        "time_service.cpp"
        "wifi_manager.cpp"
        "tcp_server.cpp"
        "discovery.cpp"
        "supabase_client.cpp"
    INCLUDE_DIRS "."
    REQUIRES
        esp_driver_gpio
        esp_driver_i2c
        esp_timer
        esp_adc
        spiffs
        nvs_flash
        unity
        esp_wifi
        esp_netif
        esp_event
        esp_driver_uart
        vfs
        lwip
        esp_http_client
        esp-tls
)
